period1 = [
    ["Adv Sem Math","Schofer","MH-312"],
    ["Adv Studies in Art","Stratton","SB-004"],
    ["Algebra II","O'Donnell","MH-102"],
    ["American Lit Tradition","ncs Greene","NCS-H414"],
    ["AP Calculus AB","Dunn","MH-314"],
    ["Biology","O'Brien","TL-110"],
    ["Case Stdy Pub Policy","Duke","MH-212"],
    ["Ceramics & Design I","ncs Sinbondit","NCS-WHart"],
    ["Chemistry","George","TL-B02"],
    ["Chinese II","ncs Xu","NCS-W219"],
    ["Chorale","Bowers","SB-206"],
    ["Chorale","Straub","SB-206"],
    ["Cities & Civilizations","Shurmer","MH-311"],
    ["Coming of Age Novel","ncs Hunt","NCS-H412"],
    ["English I","Campbell","MH-315"],
    ["English II","Licato","MH-214"],
    ["Expository Writing","Dawson","MH-213"],
    ["Hon AP Calculus BC","Kelley","MH-313"],
    ["Honors Chemistry","Van Metre","TL-004"],
    ["Honors Precalculus","Henry","SB-302"],
    ["Latin II","Johnson","TL-003"],
    ["Latin IV","King","MH-001"],
    ["Modern World Hist","Sundel","AB-101"],
    ["Music Theory","ncs Wood","NCS-H338"],
    ["Narr Race & Freedom","Hoyrd","MH-315"],
    ["Orchestra","ncs Wood",""],
    ["Precalculus","Dickson","MH-211"],
    ["Spanish IV","Castellanos Evans","MH-108"],
    ["Spanish V: Latin Am","Simon","SB-301"],
    ["Studio Art","Stratton","SB-004"],
    ["Study 1st Sem","","SB-202"],
    ["United States History","Mills","SB-100"],
    ["World Religions","Ehrenhaft","MH-103"],
    ["World Religions","Hollerith","MH-103"],
]

period2 = [
    ["Adv Studies in Art","Stratton","SB-001"],
    ["Amer Govt & Politics","Mills","MH-212"],
    ["American Modernism","Licato","MH-214"],
    ["AP Biology","Carroll","TL-111"],
    ["AP Computer Sci A","Hansen","MH-102"],
    ["AP French V","Beuchard","SB-201"],
    ["AP Latin Caesar Vergil","Johnson","TL-003"],
    ["AP Spanish V: Lang","Rusher","SB-303"],
    ["Biology","Van Metre","TL-110"],
    ["Ceramics & Design II","ncs Sinbondit","NCS-WHart"],
    ["Chemistry","George","TL-B02"],
    ["Chinese IV","ncs Xu","NCS-W219"],
    ["CW Poetry and Prose","ncs Schramm","NCS-H420"],
    ["Encountering God","Hundley","MH-213"],
    ["English I","Campbell","MH-315"],
    ["English II","Schultz","MH-103"],
    ["European Hist 1","Shurmer","MH-311"],
    ["Functions & Statistics","Findler","MH-211"],
    ["Graphic Design","ncs Dorsey","NCS-WHart"],
    ["Honors Chemistry","Errett","TL-004"],
    ["Honors Geometry","Dunn","MH-314"],
    ["Intro Chem/Mech Eng","ncs Ahlborn","NCS-W315"],
    ["Latin III","King","MH-001"],
    ["Modern World Hist","Pierce","AB-101"],
    ["Precalculus","Kelley","MH-313"],
    ["Protest in Literature","ncs Siu","NCS-H408"],
    ["Sculpture I","Stratton","SB-001"],
    ["Spanish III Honors","Castellanos Evans","MH-108"],
    ["Study 1st Sem","","SB-202"],
    ["United States History","Labaree","SB-100"],
    ["World Religions","Ehrenhaft","MH-312"],
    ["World Religions","Hollerith","MH-312"],
]

period3 = [
    ["Acting I: Foundations","ncs Snipe","NCS-W136"],
    ["Adv Studies in Art","Sturtevant","SB-001"],
    ["Algebra II","Schofer","MH-314"],
    ["American Lit Tradition","Hoyrd","MH-311"],
    ["Ancient Greek I","King","MH-001"],
    ["AP Biology","Carroll","TL-111"],
    ["AP Chemistry","George","TL-B02"],
    ["AP Environmental Sci","Errett","TL-004"],
    ["AP Physics C","Segal","TL-B01"],
    ["Biology","Van Metre","TL-110"],
    ["Creative Writing","Martínez-Leyva","MH-213"],
    ["English I","Campbell","MH-315"],
    ["English II","Licato","MH-214"],
    ["French III","Martone","LJ-104"],
    ["French IV","Beuchard","SB-201"],
    ["Geometry","Dickson","MH-312"],
    ["Geometry","O'Donnell","MH-313"],
    ["Honors Algebra II","Findler","MH-211"],
    ["Ind Study: Math","Henry",""],
    ["Intro Computer Sci","Hansen","MH-102"],
    ["Latin I","King","MH-001"],
    ["Lit & Spirituality","Ehrenhaft","MH-214"],
    ["Macroeconomics","ncs White",""],
    ["Modern Middle East","Pierce","MH-212"],
    ["Modern World Hist","Mills","AB-101"],
    ["Painting","ncs Deliyianni","NCS-WHart"],
    ["Photography I","ncs Dorsey","NCS-WHart"],
    ["Politics in America","ncs Sahr","NCS-W128"],
    ["Printmaking","Sturtevant","SB-001"],
    ["Spanish II","Rusher","MH-108"],
    ["Spanish IV Honors","Rivera","SB-303"],
    ["Stagecraft","Lampasona","MH-100"],
    ["Study 1st Sem","","SB-202"],
    ["United States History","Woods","SB-100"],
    ["Writing Politics","ncs Speranza","NCS-H400"],
]

period4 = [
    ["Adv Bio Research","O'Brien","TL-002"],
    ["Adv Studies in Art","Sturtevant","SB-004"],
    ["Algebra / Geometry A","O'Donnell","MH-313"],
    ["Algebra II","Henry","SB-302"],
    ["American Lit Tradition","ncs Greene","NCS-H414"],
    ["AP Chinese Language","ncs Xu","NCS-W219"],
    ["AP Physics 1","Segal","TL-B01"],
    ["Biology","Wheeler","TL-110"],
    ["Cities & Civilizations","Hudson","MH-311"],
    ["Drawing I","ncs Deliyianni","NCS-WHart"],
    ["English I","Campbell","MH-315"],
    ["English II","Schultz","MH-103"],
    ["Expository Writing","Dawson","MH-213"],
    ["French III","Martone","LJ-104"],
    ["Geometry","Dickson","MH-312"],
    ["Honors Chemistry","Errett","TL-004"],
    ["Latin V","ncs Sheeler","NCS-W114"],
    ["Law, Justice & Society","Robinson","MH-212"],
    ["Law, Justice & Society","Woods","MH-212"],
    ["Medieval Literature","Campbell","MH-214"],
    ["Modern World Hist","Pierce","AB-101"],
    ["Photography I","ncs Dorsey","NCS-WHart"],
    ["Precalculus","Dunn","MH-314"],
    ["Public Speaking","Bishop","MH-100"],
    ["Science Fiction","ncs Miller","NCS-H428"],
    ["Spanish II","Simon","SB-301"],
    ["Spanish III","Rivera","SB-303"],
    ["Studio Art","Sturtevant","SB-004"],
    ["Study 1st Sem","","SB-202"],
    ["United States History","Mills","SB-100"],
]

period5 = [
    ["Adv Studies in Art","Sturtevant","SB-001"],
    ["Adv Theater Design","Bishop","MH-100"],
    ["Adv Theater Design","Lampasona","MH-100"],
    ["Adv Theater Design","Liberman","MH-100"],
    ["Algebra II","Schofer","MH-312"],
    ["American Lit Tradition","Hoyrd","MH-311"],
    ["AP Biology","Carroll","TL-111"],
    ["AP Calculus AB","Dunn","MH-314"],
    ["AP Physics C","Segal","TL-B01"],
    ["Art & Design","Sturtevant","SB-001"],
    ["Biology","Wheeler","TL-002"],
    ["Calculus I","Kelley","MH-313"],
    ["Ceramics & Design I","ncs Sinbondit","NCS-WHart"],
    ["Chinese I","ncs Weeks","NCS-W112"],
    ["Comparative Lit","Schultz","MH-103"],
    ["Creative Writing","Martínez-Leyva","MH-213"],
    ["Data Science w-Python","Hansen","MH-102"],
    ["Design for Theater","Bishop","MH-100"],
    ["Design for Theater","Lampasona","MH-100"],
    ["Design for Theater","Liberman","MH-100"],
    ["Encountering God","Hundley","MH-108"],
    ["English I","Campbell","MH-315"],
    ["English II","Magaziner Mills","MH-214"],
    ["French I","ncs Bertrand","NCS-W113"],
    ["French II","Beuchard","SB-201"],
    ["Health Human Devel","Van Metre","TL-110"],
    ["Honors Algebra II","Findler","MH-211"],
    ["Honors Precalculus","Henry","SB-302"],
    ["Modern World Hist","Pierce","AB-101"],
    ["Protest in Literature","ncs Siu","NCS-H408"],
    ["Spanish II Honors","Simon","SB-301"],
    ["Spanish III","Rivera","SB-303"],
    ["Study 1st Sem","","SB-202"],
    ["United States History","Labaree","SB-100"],
    ["World Religions","Ehrenhaft","MH-001"],
    ["World Religions","Hollerith","MH-001"],
    ["Writing Politics","ncs Speranza","NCS-H400"],
]

period6 = [
    ["Adv Studies in Art","Sturtevant","SB-004"],
    ["Algebra II","Henry","SB-302"],
    ["American Lit Tradition","Licato","MH-001"],
    ["Anatomy Physiology","Virtue","NCS-W303"],
    ["AP Environmental Sci","Errett","TL-004"],
    ["AP Physics 1","Segal","TL-B01"],
    ["AP Spanish VI: Lit","Rusher","MH-103"],
    ["AP Statistics","Hansen","MH-102"],
    ["Biology","O'Brien","TL-002"],
    ["Ceramics & Design I","ncs Sinbondit","NCS-WHart"],
    ["Chinese II","ncs Xu","NCS-W219"],
    ["Chinese III","ncs Weeks","NCS-W112"],
    ["Cities & Civilizations","Shurmer","MH-311"],
    ["CW Poetry and Prose","ncs Schramm","NCS-H420"],
    ["Encountering God","Hundley","MH-108"],
    ["English I","Hoyrd","MH-315"],
    ["English II","Campbell","MH-214"],
    ["Expository Writing","Dawson","MH-213"],
    ["Geometry","O'Donnell","MH-313"],
    ["Hon Lin Alg, Vect Calc","Schofer","MH-312"],
    ["Honors History Thesis","Campbell J","MH-311"],
    ["Honors History Thesis","Labaree","MH-311"],
    ["Honors History Thesis","Shurmer","MH-311"],
    ["HSem: World Since 1945","ncs Bailey","NCS-H212"],
    ["Modern World Hist","Duke","AB-101"],
    ["Physics","George","TL-B02"],
    ["Precalculus","Dickson","MH-211"],
    ["Spanish I","Rivera","TL-303"],
    ["Spanish II","Simon","SB-301"],
    ["Studio Art","Sturtevant","SB-004"],
    ["Study 1st Sem","","SB-202"],
    ["United States History","Schaffer","SB-100"],
    ["World at War 1939-45","Labaree","MH-212"],
]

export default {
    period1,
    period2,
    period3,
    period4,
    period5,
    period6,
}